### ISSUE TITLE
Missed setting this up on https://caddyserver.com/

### ISSUE THREAD

**Issue by ldsink** [caddy-dns/tencentcloud#1]
Cannot add this package in Caddy command now.

```shell
Error: download failed: download failed: HTTP 400: dns.providers.tencentcloud is not a registered Caddy module package path (id=8222f19b-adb6-4c75-90e7-2275be9014eb)
```

**Comment by mholt** [comment]
The Go module package path would be `github.com/caddy-dns/tencentcloud` ;) (Whatever is in go.mod)

**Comment by ldsink** [comment]
In Readme this caddy module named `dns.providers.tencentcloud`, which meaning user can add this moudule by `caddy add-package dns.providers.tencentcloud`

**Comment by rehiy** [comment]
This is a new dns provider. Some functions may not be adapted ?

**Comment by ldsink** [comment]
@mholt  @rehiy  Can you help register this module in caddy like this <https://github.com/caddy-dns/googleclouddns/issues/3>

**Comment by mholt** [comment]
Oh, you can do this yourself quite easily :) Just go to https://caddyserver.com/account and claim your package!

**Comment by rehiy** [comment]
ok，i'll do that

**Comment by ldsink** [comment]
Thanks very much！

**Comment by rehiy** [comment]
done, check please
