### ISSUE TITLE
xcaddy build failure

### ISSUE THREAD

**Issue by zhzy0077** [caddy-dns/tencentcloud#4]
*Repro*
`xcaddy build --with github.com/caddy-dns/tencentcloud`

*Expected*
Successfully build.

*Actual*
```
2024/11/14 17:09:01 [INFO] exec (timeout=0s): /home/zhizhen/bin/go/go/bin/go get -v
2024/11/14 17:09:03 [INFO] Build environment ready
2024/11/14 17:09:03 [INFO] Building Caddy
2024/11/14 17:09:03 [INFO] exec (timeout=0s): /home/zhizhen/bin/go/go/bin/go mod tidy -e
2024/11/14 17:09:04 [INFO] exec (timeout=0s): /home/zhizhen/bin/go/go/bin/go build -o /home/zhizhen/caddy -ldflags -w -s -trimpath -tags nobadger,nomysql,nopgx
# github.com/caddyserver/caddy/v2
/home/zhizhen/go/pkg/mod/github.com/caddyserver/caddy/v2@v2.8.4/context.go:541:12: undefined: zapslog.HandlerOptions
2024/11/14 17:09:04 [INFO] Cleaning up temporary folder: /tmp/buildenv_2024-11-14-1708.1373625778
2024/11/14 17:09:04 [FATAL] exit status 1
```

**Comment by kkkgo** [comment]
I am experiencing the same issue and error as described. I have been using GitHub Actions to automatically build Caddy with this plugin. However, since around two weeks ago, the build process consistently fails when including this plugin.

**Comment by wangzexi** [comment]
When I revert [this](https://github.com/caddy-dns/tencentcloud/pull/3) merge, everything's fine.

 Hope @ysicing have a look.

**Comment by CameronMunroe** [comment]
The current tagged release is still broken it seems. 

If the master branch is working, could we create a new tag against it as that is the default spot for the xcaddy builder to pull from.
